[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
  \.eggs/|
  \.git/|
  \.hg/|
  \.mypy_cache/|
  \.tox/|
  \.venv/|
  .nox/|
  docs/|
  build/|
  dist/|
  \.nox/
)/
'''

[tool.isort]
skip_glob = ".nox/**/*.py"
multi_line_output = 3
line_length = 88
force_single_line = true
known_third_party = [
  "django",
  "flask",
  "numpy",
  "pandas",
  "pytest",
  "requests",
]